### ISSUE TITLE
Request: For the Custom Date|Time stamp allow user to hit <enter> rather than click the button

### ISSUE THREAD

**Issue by bobcat-hubcap** [Gru80/obsidian-timestamper#4]
The <Insert Date|Time> confirmation button should be able to be activated by user hitting <Enter>. Currently, does not work that way in  Obsidian v.0. 14.15

Many thanks.

**Comment by MaxSamusevich** [comment]
> The <Insert Date|Time> confirmation button should be able to be activated by user hitting . Currently, does not work that way in Obsidian v.0. 14.15
> 
> Many thanks.

I have the same issue today after the latest update. This plugin is my number 1 plugin I use 24/7 and always hit Enter. No it's super inconvenient to click on the button. 

I also wish to have an option to set the custom format for date and time and never be prompted to confirm because I always use the same format and spend thousands times a day to confirm I really want exactly this format. 

@Gru80, please, fix the problem with currently not working Enter confirmation of custom format and add an option to insert custom string without confirmation the format. Thank you for this awesome and very useful for me plugin ❤

**Comment by Daza99** [comment]
I was going to request this very thing too. I didn't realize the enter key used to work in previous versions of Obs. Hopefully this can be fixed soon.

**Comment by Gru80** [comment]
Hi, 

beside open issue with the <Enter> key closing the dialog, I want to point out one thing that might be extremely handy for you if you use the same template string four your date/time stamp:

You can configure a 
- preconfigured time stamp
- preconfigured date stamp

in the TimeStamper Settings (in the "Community Plugins" section):
![image](https://user-images.githubusercontent.com/30384872/197145771-fa8677d1-754f-452e-83ab-4f7103ca7d99.png)

and then configure a shortcut  key for your preconfigured time and date stamp in the Hotkeys-Setting (in the "Options" menu):
![image](https://user-images.githubusercontent.com/30384872/197146008-c07d87db-c6b3-4620-8cc7-7428145c2f0f.png)

With this setup, you can simply insert your preconfigured custom time and date stamp with a simple press of the hotkey, so you don't even need the dialogue to be opened

**Comment by Gru80** [comment]
this is now included in version 1.3.0 of the plugin which was just released
